import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import ThemeSwitcher from "./ThemeSwitcher";
export const metadata: Metadata = {
  title: "M.S Traders",
  description: "Generated by Mohammad Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {/* <ThemeSwitcher /> */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
